# 第3章 Python的数据结构、函数和文件

In [1]:
tup=4,5,6
tup

(4, 5, 6)

In [2]:
tuple([1,2,3])

(1, 2, 3)

In [3]:
tuple("woaini")

('w', 'o', 'a', 'i', 'n', 'i')

In [4]:
("love","you")*3

('love', 'you', 'love', 'you', 'love', 'you')

In [5]:
a,b,c=tup
a

4

In [6]:
c

6

In [7]:
b

5

In [11]:
a,b=1,2
a,b=b,a
b

1

In [12]:
seq=[1,2],3,4
a,b,c=seq
a

[1, 2]

In [14]:
v=1,2,3,4,5
n,m,*_=v
n,m

(1, 2)

In [15]:
_

[3, 4, 5]

In [16]:
a=[1,2,2,3,4,5]
a.count(2)

2

In [17]:
gen=range(10)
gen

range(0, 10)

In [18]:
type(gen)

range

In [21]:
a=list(gen)

In [22]:
gen,a

(range(0, 10), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a.append(123)
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 123]

In [24]:
a.insert(0,15)

In [25]:
a

[15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 123]

In [26]:
a.pop(3)
a

[15, 0, 1, 3, 4, 5, 6, 7, 8, 9, 123]

In [27]:
a.pop()

123

In [28]:
a

[15, 0, 1, 3, 4, 5, 6, 7, 8, 9]

In [29]:
a.pop(-1)
a

[15, 0, 1, 3, 4, 5, 6, 7, 8]

In [30]:
a.append(3)
a

[15, 0, 1, 3, 4, 5, 6, 7, 8, 3]

In [31]:
a.remove(3)
a

[15, 0, 1, 4, 5, 6, 7, 8, 3]

In [32]:
4,5 in a

(4, True)

In [33]:
(4,5) in a

False

In [34]:
4 in a

True

用extend代替+，速度更快：

In [35]:
a.extend(55,66,88)
a

TypeError: extend() takes exactly one argument (3 given)

In [36]:
a.extend([55,66,88])
a

[15, 0, 1, 4, 5, 6, 7, 8, 3, 55, 66, 88]

In [37]:
a.sort()

In [38]:
a

[0, 1, 3, 4, 5, 6, 7, 8, 15, 55, 66, 88]

In [2]:
b=["abc","a","12345"]
b.sort(key=len)
b

['a', 'abc', '12345']

In [5]:
import bisect
c=[1,2,2,2,3,4,7]
bisect.insort(c,5)
c

[1, 2, 2, 2, 3, 4, 5, 7]

In [15]:
bisect.bisect(c,5)

8

In [16]:
seq=[7,2,3,7,5,6,0,1]
seq[1:5]

[2, 3, 7, 5]

In [17]:
seq[-6:-2]

[3, 7, 5, 6]

In [18]:
seq[::2]

[7, 3, 5, 0]

In [19]:
seq[::-1]

[1, 0, 6, 5, 7, 3, 2, 7]

In [28]:
some_list=['foo','bar','baz']
mapping={}
for i,v in enumerate(some_list):
    mapping[v]=i
mapping

{'bar': 1, 'baz': 2, 'foo': 0}

In [32]:
a=[('b',1),('a',2)]
sorted(a,key=lambda x:x[0])

[('a', 2), ('b', 1)]

In [34]:
for i in sorted("bcadfr"):
    print(i)

a
b
c
d
f
r


In [37]:
seq1=[1,2,3]
seq2=[4,5,6]
seq3=[7,8]
list(zip(seq1,seq2,seq3))

[(1, 4, 7), (2, 5, 8)]

In [39]:
e={'(':')','{':'}','[':']'}
e

{'(': ')', '[': ']', '{': '}'}

In [40]:
'[' in e

True

In [41]:
del e['[']
e

{'(': ')', '{': '}'}

In [43]:
list(e.keys())

['(', '{']

In [45]:
mapping=dict(zip(range(5),reversed(range(5))))
mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

In [58]:
str1=['a','abcd','ab','abc']
[i.upper() for i in str1 if len(i)>2 ]

['ABCD', 'ABC']

In [59]:
{len(x) for x in str1}

{1, 2, 3, 4}

In [60]:
{val: index for index,val in enumerate(str1)}

{'a': 0, 'ab': 2, 'abc': 3, 'abcd': 1}

In [61]:
{a:b for a,b in enumerate(str1)}

{0: 'a', 1: 'abcd', 2: 'ab', 3: 'abc'}

In [62]:
str1.sort(key=lambda x :len(x))
str1

['a', 'ab', 'abc', 'abcd']

In [66]:
def sum(a,b):
    return a+b
add=lambda x : sum(5,x)

In [67]:
add(6)

11

In [69]:
gen=(x**2 for x in range(10))
list(gen)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [71]:
def abc(x):
    try:
        return float(x)
    except:
        return x
abc("abc")

'abc'

In [72]:
abc(123)

123.0

# 第4章 numpy基础：数组和矢量计算

In [2]:
import numpy as np
data=np.random.randn(2,3)
data

array([[ 0.90067016,  1.16675203,  2.47916726],
       [-0.32033279,  0.2449339 , -0.11329886]])

In [3]:
data*10

array([[  9.00670157,  11.66752027,  24.7916726 ],
       [ -3.20332794,   2.44933902,  -1.13298861]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

In [12]:
# ndarray:多维数组 【np.array】
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1.shape

(5,)

In [13]:
data2=[[1,2,3],[4,5,6]]
arr2=np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2.shape

(2, 3)

In [15]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [19]:
# 注意是（3,3）不是3,3
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [21]:
np.arange(4).shape

(4,)

In [22]:
arr1=np.array([1,2,3],dtype=np.float64)

In [27]:
arr2=arr1.astype(np.int64)
arr2.dtype

dtype('int64')

In [29]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
arr=np.arange(10)
arr[5:8]

array([5, 6, 7])

In [33]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [34]:
arr_slice=arr[5:8]
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [35]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [36]:
arr3=arr_slice.copy()
arr3[1]=12345
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [37]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d[1,0]

array([7, 8, 9])

In [41]:
arr3d[1,0]=[1,1,1]
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 1,  1,  1],
        [10, 11, 12]]])

In [3]:
import numpy as np
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [5]:
arr2d[:2,:1]

array([[1],
       [4]])

In [7]:
arr2d[1,:2]

array([4, 5])

In [8]:
arr2d[0,2:]

array([3])

In [9]:
arr2d[:,:1]

array([[1],
       [4]])

In [14]:
arr2d[:1,1:]=0
arr2d

array([[1, 0, 0],
       [4, 5, 6]])

In [16]:
names=np.array(['bob','joe','will','bob','will','joe','joe'])
data=np.random.randn(7,4)
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'],
      dtype='<U4')

In [17]:
data

array([[-1.25328823, -0.57888623,  1.67581337, -0.84795836],
       [-0.76795622,  1.66695605,  0.11090051, -0.53138149],
       [-2.29690509, -0.8543138 , -0.38986941, -0.42456222],
       [ 1.04749665, -1.8340274 , -0.98065263, -0.22423564],
       [ 0.31873778,  0.39974682,  2.11061884, -0.47953007],
       [ 1.13062454,  0.0042576 , -0.20316628,  0.58331122],
       [ 0.76622874, -1.83774319,  0.46630098, -1.0764666 ]])

In [18]:
names=='bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [19]:
data[names=='bob']

array([[-1.25328823, -0.57888623,  1.67581337, -0.84795836],
       [ 1.04749665, -1.8340274 , -0.98065263, -0.22423564]])

In [20]:
data[names=='bob',2:]

array([[ 1.67581337, -0.84795836],
       [-0.98065263, -0.22423564]])

In [24]:
cond=names=="bob"
cond

array([ True, False, False,  True, False, False, False], dtype=bool)

In [25]:
data[~cond]

array([[-0.76795622,  1.66695605,  0.11090051, -0.53138149],
       [-2.29690509, -0.8543138 , -0.38986941, -0.42456222],
       [ 0.31873778,  0.39974682,  2.11061884, -0.47953007],
       [ 1.13062454,  0.0042576 , -0.20316628,  0.58331122],
       [ 0.76622874, -1.83774319,  0.46630098, -1.0764666 ]])

In [26]:
mask=(names=='bob')|(names=='will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [28]:
data[data<0]=0
data

array([[ 0.        ,  0.        ,  1.67581337,  0.        ],
       [ 0.        ,  1.66695605,  0.11090051,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.04749665,  0.        ,  0.        ,  0.        ],
       [ 0.31873778,  0.39974682,  2.11061884,  0.        ],
       [ 1.13062454,  0.0042576 ,  0.        ,  0.58331122],
       [ 0.76622874,  0.        ,  0.46630098,  0.        ]])

In [32]:
arr=np.empty((8,4))
arr

array([[  2.05833592e-312,   2.14321575e-312,   1.29441743e-312,
          2.37663529e-312],
       [  2.05833592e-312,   2.41907520e-312,   2.56761491e-312,
          1.93101617e-312],
       [  2.07955588e-312,   2.07955588e-312,   9.33678148e-313,
          2.24931554e-312],
       [  2.14321575e-312,   9.33678148e-313,   2.52517499e-312,
          2.29175545e-312],
       [  8.27578359e-313,   8.27578359e-313,   2.35541533e-312,
          8.27578359e-313],
       [  8.27578359e-313,   2.22809558e-312,   2.29175545e-312,
          9.33678148e-313],
       [  2.24931554e-312,   2.14321575e-312,   9.33678148e-313,
          2.24931554e-312],
       [  2.14321575e-312,   1.97345609e-312,   1.97345609e-312,
          0.00000000e+000]])

In [34]:
for i in range(8):
    arr[i]=i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

### 感觉下面的花式索引比较重要：
花式索引和切片不一样，总是将数组复制到新数组中。
切片是得到视图，在原数据中修改。

In [38]:
arr[[-1,-2,-3]]

array([[ 7.,  7.,  7.,  7.],
       [ 6.,  6.,  6.,  6.],
       [ 5.,  5.,  5.,  5.]])

In [57]:
arr[[-3,-2,-1]]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [59]:
#先选取行axis=0，再从选出的行中选位置分别再0，3,1,2的值。

arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [44]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 数组转置与轴对换：

In [60]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
arr[[-1]]


array([[10, 11, 12, 13, 14]])

In [62]:
arr[[-1]].shape

(1, 5)

In [63]:
# 获取7
arr[[1],[2]]

array([7])

In [64]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [65]:
arr.T.shape

(5, 3)

In [66]:
arr=np.random.randn(6,3)
np.dot(arr.T,arr)

array([[ 3.50811513,  0.27085911,  3.7248265 ],
       [ 0.27085911,  2.48779951,  1.94730711],
       [ 3.7248265 ,  1.94730711,  7.32041835]])

In [68]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [69]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

### 利用数组进行数据处理：

In [72]:
arr=np.arange(10)
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [73]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [75]:
arr=np.arange(-5,5,0.01)
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [77]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result=np.where(cond,xarr,yarr)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [79]:
arr=np.random.randn(4,4)
arr

array([[-0.30061262, -0.97402894,  0.64284372,  1.05151771],
       [ 0.17861968, -0.07992159,  0.57049416, -0.53903755],
       [ 1.38934551,  0.30970607,  0.60660651, -0.47315818],
       [ 0.56319226,  0.46045806, -0.30017441,  1.01334397]])

In [80]:
np.where(arr>0,2,-2)

array([[-2, -2,  2,  2],
       [ 2, -2,  2, -2],
       [ 2,  2,  2, -2],
       [ 2,  2, -2,  2]])

In [81]:
arr

array([[-0.30061262, -0.97402894,  0.64284372,  1.05151771],
       [ 0.17861968, -0.07992159,  0.57049416, -0.53903755],
       [ 1.38934551,  0.30970607,  0.60660651, -0.47315818],
       [ 0.56319226,  0.46045806, -0.30017441,  1.01334397]])

#### 感觉这个在softmax里经常用到：

In [82]:
arr.sum(axis=0)

array([ 1.83054483, -0.28378641,  1.51976998,  1.05266595])

In [83]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [84]:
np.ones(3)

array([ 1.,  1.,  1.])

In [92]:
samples=np.random.normal(size=(4,4))
samples

array([[ 2.88674595,  2.09164881,  0.84630337,  0.32774623],
       [-1.20343312,  0.19388961,  0.37296414,  1.8336297 ],
       [-0.107123  , -0.46933473, -0.09942769,  0.80506711],
       [-0.64689036,  0.50209719, -0.54860613, -0.64515312]])

In [94]:
abc=[1,2,3,4]
#shuffle 随机打乱
np.random.shuffle(abc)
abc

[2, 3, 1, 4]

### 随机漫步：

In [98]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()
walk.max()

29

In [99]:
(np.abs(walk) >= 10).argmax()

55